import type { Metadata } from "next";
import { Inter } from "next/font/google";
import styles from "@/app/page.module.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// declare global {
//   interface Window {
//     kakao: any;
//     Kakao: any;
//     IMP: any;
//   }
// }
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={styles.container}>{children}</div>
      </body>
    </html>
  );
}
